branch_whitelist = ["main"]

ignore_merge_commits = true

pre_bump_hooks = [
    "uv version {{version}}"
]

# A list of command to run AFTER creating a version
post_bump_hooks = [
    "git push",
    "git push origin {{version}}"
]

# Changelog configuration
[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "https://git.h.oluflorenzen.de"
repository = "immich-prometheus-exporter"
owner = "finkregh"