on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
          fetch-tags: true

      - uses: https://git.h.oluflorenzen.de/mirrors/codeberg.PurpleBooth.common-pipelines/actions/install-cocogitto@main
        name: Install cocogitto

      - name: Configure Git User
        uses: https://git.h.oluflorenzen.de/mirrors/codeberg.PurpleBooth.common-pipelines/actions/configure-git-user@main

      - uses: https://git.h.oluflorenzen.de/mirrors/codeberg.PurpleBooth.common-pipelines/actions/release-with-cog@main
        name: Release with cocogitto

      - name: Install uv and set the python version
        uses: https://github.com/astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Cache state
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          TERM: "dumb"
        run: uv run pytest --color=yes tests

      - name: Build
        run: uv build

      - name: Publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PACKAGE_UPLOAD_TOKEN }}
          UV_PUBLISH_INDEX: ${{ github.server_url }}/api/packages/finkregh/pypi
        run: |
          echo $UV_PUBLISH_INDEX
          uv publish
