on:
  push:
    branches:
      - main
jobs:
  build:
    name: Bump version, build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
          fetch-tags: true
        
      - name: Install uv and set the python version
        uses: https://github.com/astral-sh/setup-uv@v6
        id: setup-uv
        with:
          python-version: "3.13"
          enable-cache: true
          prune-cache: false

      - uses: https://git.h.oluflorenzen.de/mirrors/codeberg.PurpleBooth.common-pipelines/actions/install-yq@main
        name: Install yq

      - uses: https://git.h.oluflorenzen.de/mirrors/codeberg.PurpleBooth.common-pipelines/actions/install-cocogitto@main
        name: Install cocogitto

      - name: Configure Git User
        uses: https://git.h.oluflorenzen.de/mirrors/codeberg.PurpleBooth.common-pipelines/actions/configure-git-user@main

      - name: Release with cocogitto
        uses: https://git.h.oluflorenzen.de/mirrors/codeberg.PurpleBooth.common-pipelines/actions/release-with-cog@main

      - name: Cache state
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          TERM: "dumb"
        run: uv run pytest --color=yes tests

      - name: Build
        run: uv build

      - name: Publish
        env:
          UV_PUBLISH_USERNAME: finkregh
          UV_PUBLISH_PASSWORD: ${{ secrets.PACKAGE_UPLOAD_TOKEN }}
          #UV_PUBLISH_INDEX: ${{ github.server_url }}/api/packages/finkregh/pypi
          UV_PUBLISH_URL: ${{ github.server_url }}/api/packages/finkregh/pypi
        run: |
          uv publish -v
