on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Unittests and try build -- Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - name: show tmpdir
        run: |
          echo "cache dir ${RUNNER_TEMP}"
          ls -la ${RUNNER_TEMP}/*

      - name: Install uv and set the python version
        uses: https://github.com/astral-sh/setup-uv@v6
        id: setup-uv
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          prune-cache: false

      - name: Cache state
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"

      - name: show tmpdir
        run: |
          echo "cache dir ${RUNNER_TEMP}"
          ls -la ${RUNNER_TEMP}/*

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          TERM: "dumb"
        run: uv run pytest --color=yes tests

      - name: Build
        run: uv build

      - name: install and run the project
        run: |
          echo "cache dir ${RUNNER_TEMP}"
          ls -la ${RUNNER_TEMP}/*
          uv sync --locked --all-extras --dev
          uv run immich-prometheus-exporter --help


#    - name: Save uv cache
#      uses: actions/cache/save@v4.2.4
#      with:
#        path: ${{ env.}}
#        key: setup-uv-${{ hashFiles('**/*requirements*.txt','**/*requirements*.in',**/*constraints*.txt','**/*constraints*.in','**/pyproject.toml','**/uv.lock') }}
