on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Unittests and try build -- Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".forgejo/workflows/*.ya?ml"]'

      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: https://github.com/astral-sh/setup-uv@v6
        id: setup-uv
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          prune-cache: false

      - name: Cache state
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          TERM: "dumb"
        run: uv run pytest --color=yes tests

      - name: Build
        run: uv build

      - name: install and run the project
        run: |
          uv sync --locked --all-extras --dev
          uv run immich-prometheus-exporter --help
