{
 "title": "Immich Library Stats",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "Users",
    "query": {
     "query": "label_values(immich_user_photos,user_name)"
    }
   },
   {
    "name": "library",
    "label": "External Library",
    "query": {
     "query": "label_values(immich_library_photos_count,library_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Assets Growth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Images vs Videos sum (change over $__interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(immich_user_photos{user_name=~\"$user\"}[$__rate_interval]))",
     "legendFormat": "Images"
    },
    {
     "expr": "sum(rate(immich_user_videos{user_name=~\"$user\"}[$__rate_interval]))",
     "legendFormat": "Videos"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Images vs Videos per user (change over $__interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(user_name) (rate(immich_user_photos{user_name=~\"$user\"}[$__rate_interval]))",
     "legendFormat": "Images {{user_name}}"
    },
    {
     "expr": "sum by(user_name) (rate(immich_user_videos{user_name=~\"$user\"}[$__rate_interval]))",
     "legendFormat": "Videos {{user_name}}"
    }
   ]
  },
  { "title": "Assets Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total assets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(immich_user_photos{user_name=~\"$user\"} + immich_user_videos{user_name=~\"$user\"})",
     "legendFormat": "{{user_name}}"
    },
    {
     "expr": "sum(immich_user_photos{user_name=~\"$user\"} + immich_user_videos{user_name=~\"$user\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total assets growth over $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(user_name) ((rate(immich_user_photos{user_name=~\"$user\"}[$__rate_interval]) + rate(immich_user_videos{user_name=~\"$user\"}[$__rate_interval])))",
     "legendFormat": "{{user_name}}"
    },
    {
     "expr": "sum((rate(immich_user_photos[$__rate_interval]) + rate(immich_user_videos[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Images",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "immich_user_photos{user_name=~\"$user\"}",
     "legendFormat": "{{user_name}}"
    },
    {
     "expr": "sum(immich_user_photos{user_name=~\"$user\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Videos",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "immich_user_videos{user_name=~\"$user\"}",
     "legendFormat": "{{user_name}}"
    },
    {
     "expr": "sum(immich_user_videos{user_name=~\"$user\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Images/Videos per user - $user",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "user",
   "collapsed": true,
   "panels": [
    {
     "title": "Images vs Videos (count)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "immich_user_photos{user_name=~\"$user\"}",
       "legendFormat": "Images"
      },
      {
       "expr": "immich_user_videos{user_name=~\"$user\"}",
       "legendFormat": "Videos"
      }
     ]
    },
    {
     "title": "Images vs Videos (change over $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(immich_user_photos{user_name=~\"$user\"}[$__rate_interval]))",
       "legendFormat": "Images"
      },
      {
       "expr": "sum(rate(immich_user_videos{user_name=~\"$user\"}[$__rate_interval]))",
       "legendFormat": "Videos"
      }
     ]
    }
   ]
  },
  { "title": "etc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Library asset count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "immich_library_photos_count{library_name=~\"$library\"}",
     "legendFormat": "{{library_name}} - Photos"
    },
    {
     "expr": "immich_library_videos_count{library_name=~\"$library\"}",
     "legendFormat": "{{library_name}} - Videos"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "immich_storage_disk_use_bytes", "legendFormat": "Disk usage" }
   ]
  },
  {
   "title": "Disk usage growth over $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(immich_storage_disk_use_bytes{ }[$__rate_interval]))",
     "legendFormat": "Disk usage"
    }
   ]
  },
  {
   "title": "Album stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "immich_albums_owned_total", "legendFormat": "Albums owned" },
    { "expr": "immich_albums_shared_total", "legendFormat": "Albums shared" },
    { "expr": "immich_albums_not_shared_total", "legendFormat": "Albums not shared" }
   ]
  }
 ]
}